import { Inter } from "next/font/google";

import "@/styles/globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "NextBlog",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#111] text-[#bbb] ${inter.className}`}>
        <Navbar />
        <main className="container mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
